name: Test Cron

on:
  schedule:
    # 每天 UTC 时间 0 点执行一次
    - cron: '*/5 * * * *'
  workflow_dispatch: # 手动触发测试用

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check date
        run: date
      - name: Echo test
        run: echo "GitHub Cron is working!"
