name: Sync Random Part of JSON File

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:     # 允许手动触发

jobs:
  sync-json:
    runs-on: ubuntu-latest

    steps:
      # 1. 下载源 JSON 文件
      - name: Download source JSON
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -sL https://raw.githubusercontent.com/OFXIV/sources-private/main/json/music.json

      # 2. 随机抽取部分数组元素
      - name: Extract random part
        run: |
          node -e "
          const fs = require('fs');
          const data = JSON.parse(fs.readFileSync('source.json', 'utf8'));
          const n = 14; // 随机抽取数量，可修改
          const shuffled = data.sort(() => 0.5 - Math.random());
          const partial = shuffled.slice(0, n);
          fs.writeFileSync('partial.json', JSON.stringify(partial, null, 2));
          "

      # 3. 使用 GitHub API 更新目标仓库文件
      - name: Update target file via GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          file_path="json/music.json"
          repo="sources"
          branch="main"
          content=$(base64 -w 0 partial.json)
          sha=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$repo/contents/$file_path?ref=$branch" | jq -r .sha)
          curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/$repo/contents/$file_path \
            -d "{\"message\": \"Sync random part of JSON from source repo\", \"content\": \"$content\", \"sha\": \"$sha\", \"branch\": \"$branch\"}"
